source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '7.0'

pod 'google-plus-ios-sdk'
pod 'AFNetworking', '~> 1.3.3'
pod 'SDWebImage'
pod 'NSDate+TimeAgo'
pod 'FlurrySDK'
pod 'OHAttributedStringAdditions'
pod 'Reachability', '~> 3.1.1'
pod 'Objective-C-HMTL-Parser', '~> 0.0.1'
pod 'WYPopoverController'
pod 'uidevice-extension'
pod 'YTVimeoExtractor'
pod 'MBProgressHUD'
pod 'BTBadgeView', '~> 1.2'
pod 'Facebook-iOS-SDK', '~> 3.22'
pod 'ParseFacebookUtils', '~> 1.2'
